name: Deploy to Staging

on:
  push:
    branches:
      - master
      - staging
      - subscribers-email
      - newsletter-email-endpoint

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.ESUBALEW_MAC_SSH_PRIVATE_KEY }}  # Access SSH key from secrets.

    - name: Test SSH Connection to Jump Server (Add Jump Server to Known Hosts)
      run: |
        ssh -o StrictHostKeyChecking=no esubalew@${{ secrets.JUMP_SERVER_IP }} "echo 'Connected to Jump Server!'"
        
    - name: Sync Files to Jump Server
      run: |
        scp -r * esubalew@${{ secrets.JUMP_SERVER_IP }}:/home/esubalew/efs/wp-content/plugins/mp-mailing-list
